### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Abhi1892** [qing762/exitLag-auto-signup#1]
at the end ,
ExitLag account registration failed!
Exiting...
is produced

**Comment by qing762** [comment]
It is now patched by ExitLag
I'll update this repo soon

**Comment by hiez1337** [comment]
The error still appears. At the end of registration it says:

Email request successfully responded with a status code of 200
Fetching email address success!
Token: ********************
Email address: ********************

ExitLag account registration failed!
Exiting...

![image](https://github.com/qing762/exitLag-auto-signup/assets/44944483/0c070c9d-0117-49b3-be56-bdd9c89d4843)

**Comment by sledokk** [comment]
Hello! As far as I know, ExitLag detects temporary mail and you cannot register an account with it, would you like to try using rambler.ru? I have seen several automatic rambler authorizations for python on github. This is a very interesting topic for me, I hope you will update it, thank you!

**Comment by qing762** [comment]
> Hello! As far as I know, ExitLag detects temporary mail and you cannot register an account with it, would you like to try using rambler.ru? I have seen several automatic rambler authorizations for python on github. This is a very interesting topic for me, I hope you will update it, thank you!

Sorry for the late reply, was away for exam recently. Sadly I won't be using rambler.ru for now.
[I'll be using mail.tm](https://mail.tm/en/)

**Comment by qing762** [comment]
Seems like ExitLag changed their method on how captcha works
From hCaptcha to ReCaptcha

**Comment by qing762** [comment]
Fixed. 5abc652e139a797ddf59d8ea785b77715912d141
