### ISSUE TITLE
n

### ISSUE THREAD

**Issue by skil44444444444** [qing762/exitlag-auto-signup#10]
![image](https://github.com/qing762/exitlag-auto-signup/assets/151251646/845b6444-6b1a-4bea-be66-e2efb7aeebf4)

**Comment by skil44444444444** [comment]
![image](https://github.com/qing762/exitlag-auto-signup/assets/151251646/48f048e1-e9bd-46c0-b0ba-0e542e4ee23a)

**Comment by qing762** [comment]
You are running it in the `Gaming` folder instead of the `exitLag-auto-signup` folder

**Comment by skil44444444444** [comment]
![image](https://github.com/qing762/exitlag-auto-signup/assets/151251646/05177e5c-56f4-4b4f-9c2f-e380663bd335)
