### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by skil44444444444** [qing762/exitlag-auto-signup#12]
![image](https://github.com/qing762/exitlag-auto-signup/assets/151251646/21bc5685-7647-4c62-b49d-d65229ab4b86)

**Comment by skil44444444444** [comment]
the script works but this happens after i input the login credentials in

**Comment by qing762** [comment]
I only got two reports (including you) who face this issues. Try creating another account.
![image](https://github.com/qing762/exitlag-auto-signup/assets/59680329/5032ef0b-d232-4af5-ba41-01019ffdf4fa)
