### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Ahmad-2213** [qing762/exitlag-auto-signup#20]
HI there. when you type "y" to block IP , it says you don't have the permission to do this.
also , using the other types of mails rather than default gives me errors.
but it worked via VPN and thanks a LOT! don't give up , you're helping many players.

**Comment by qing762** [comment]
Run the script as administrator (Note that this is only required once for initial setup)
Regarding the email problem, this will be fixed as soon as possible.
Thanks a lot for your support!

**Comment by Ahmad-2213** [comment]
> r support!

I did it, didn't work.
waiting for the new update! 
Thanks.

**Comment by qing762** [comment]
Fixed in e538a26
