### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by skil44444444444** [qing762/exitlag-auto-signup#7]
I've done git clone https://github.com/qing762/exitLag-auto-signup/ but i do not understand how to proceed with pip install -r requirements.txt
![image](https://github.com/qing762/exitlag-auto-signup/assets/151251646/570aa4c3-b297-4b29-aaff-868a7fc89cf8)

**Comment by qing762** [comment]
Use Powershell/CMD
You're using Python's terminal, which you cant download packages in it

**Comment by skil44444444444** [comment]
![image](https://github.com/qing762/exitlag-auto-signup/assets/151251646/be08aabe-166a-4e72-8d78-dc8ae06f5e70)

**Comment by qing762** [comment]
> ![image](https://user-images.githubusercontent.com/151251646/284026701-be08aabe-166a-4e72-8d78-dc8ae06f5e70.png)

Python is not added to `PATH`. [Refer to this video to install it](https://www.youtube.com/watch?v=fJKdIf11GcI)
