### ISSUE TITLE
requirements.txt not found?

### ISSUE THREAD

**Issue by SagMestKing** [qing762/exitlag-auto-signup#9]
Somehow the requirements.txt doesn't exist when I already cloned the repository.

![image_2023-11-23_145521697](https://github.com/qing762/exitlag-auto-signup/assets/151835572/24ec523c-6618-446b-a7dd-abd3021ee560)
![image_2023-11-23_145646605](https://github.com/qing762/exitlag-auto-signup/assets/151835572/0b70948c-bc18-4b24-b1c6-4a29035162e0)

**Comment by qing762** [comment]
You are running it in the `System32` folder instead of the `exitLag-auto-signup` folder
